package quancity.client.common;

// The Enum in Java is a data type which contains a fixed set of constants

public enum ApiEnum {
	CITY_CREATE, CITY_UPDATE, CITY_GET_ONE, DELETE, CITY_FIND_ALL, CLOSE_CONNECTION, TRAMWAY_GET_ONE, TRAMWAY_UPDATE,
	TRAMWAY_MAP_RANDOM, CITY_DELETE, SENSORAIR_CREATE, SENSORAIR_UPDATE, SENSORAIR_FIND_ONE, SENSORAIR_FIND_ALL,
	SENSORAIR_FIND_ACTIVE, SENSORAIR_DELETE, ALERT_HISTORY_FIND_ALL, ALERT_UPDATE, VEHICULESENSOR_CREATE,
	VEHICULESENSOR_UPDATE, VEHICULESENSOR_FIND_ONE, VEHICULESENSOR_FIND_ALL, VEHICULESENSOR_DELETE, THRESHOLD_CREATE,
	THRESHOLD_UPDATE, THRESHOLD_FIND_ONE, THRESHOLD_FIND_ALL, THRESHOLD_DELETE, ActualData_FIND_ALL,
	CarbonData_FIND_ALL, ANALYSE_TODAY, ANALYSE_DATE, ANA_DAILY_INFO
}
